float:
  any:
  - base_args: ['@metric']
    constructor: Qdrant
    disabled: false
    docker_tag: ann-benchmarks-qdrant
    module: ann_benchmarks.algorithms.qdrant
    name: qdrant
    run_groups:
      default:
        args: [
          ['none', 'scalar'], #quantization
          [ 8, 16, 32, 64 ], #m
          [ 64, 128, 512 ], #ef_construct
        ]
        query_args: [
          [null, 16, 32, 64, 128, 512, 768], #hnsw_ef
          [True, False], # re-score
        ]
